# Generated by Django 2.2.5 on 2019-09-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSite',
            fields=[
                ('Site_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Site_Name', models.CharField(max_length=50)),
                ('Site_Location', models.CharField(max_length=50)),
                ('Site_Department', models.CharField(max_length=50)),
                ('Site_Code', models.CharField(max_length=50)),
                ('Organization_ID', models.IntegerField()),
                ('Organization_Name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['Site_Name'],
            },
        ),
    ]
